### ISSUE TITLE
The question about the "ReferenceCoefficienttoPerformance" of the Air Source Heat Pump

### ISSUE THREAD

**Issue by balont666** [MingboPeng/Ironbug#128]
Hello, Mingbo! Very inspired about Ironbug and already testing it!.. Unfortunately, i have a problem. When i use the "Air Source Heat Pump" of the battery called "HVACTemplate", i find that there is nothing change about the cooling energy result and heating energy result if i change the number of  "ReferenceCoefficienttoPerformance". I'm very confused about this. I would be glad to have your advice!!!

**Comment by MingboPeng** [comment]
Hi @balont666 thanks for testing it. But this is not a development-related question, I would suggest you post this question to the forum: https://discourse.ladybug.tools, so that others could also help you.

I see your question is more about the question about EnergyPlus, you can find more information from EnergyPlus's Input and Output Reference: https://bigladdersoftware.com/epx/docs/23-2/input-output-reference/group-plant-equipment.html#plhp_eir_cooling
